version: '3.8'

services:
  # 应用服务
  app:
    image: ghcr.io/skyhhjmk/windblog:latest
    container_name: windblog_app
    ports:
      - "8787:8787"
    volumes:
      - .:/var/www/html
      - ./runtime:/var/www/html/runtime
    environment:
      - DB_PGSQL_HOST=postgres
      - DB_PGSQL_PORT=5432
      - DB_PGSQL_DATABASE=windblog
      - DB_PGSQL_USERNAME=windblog
      - DB_PGSQL_PASSWORD=windblog_secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_DRIVER=redis
      - APP_DEBUG=true
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - windblog_network
    command: php start.php start

  # PostgreSQL 数据库
  postgres:
    image: postgres:18-alpine
    container_name: windblog_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=windblog
      - POSTGRES_USER=windblog
      - POSTGRES_PASSWORD=windblog_secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U windblog" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - windblog_network

  # Redis 缓存
  redis:
    image: redis:8-alpine
    container_name: windblog_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - windblog_network
    command: redis-server --appendonly yes

  # RabbitMQ 消息队列
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: windblog_rabbitmq
    ports:
      - "5672:5672"   # AMQP 端口
      - "15672:15672" # 管理界面
    environment:
      - RABBITMQ_DEFAULT_USER=windblog
      - RABBITMQ_DEFAULT_PASS=windblog_secret
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - windblog_network

  # ElasticSearch 搜索引擎（可选）
  elasticsearch:
    image: elasticsearch:9.1.3
    container_name: windblog_elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1G -Xmx2G"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - windblog_network

  # Nginx (可选，用于生产环境)
  nginx:
    image: nginx:alpine
    container_name: windblog_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html/public:ro
      - ./compose/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - windblog_network
    profiles:
      - production

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local
  elasticsearch_data:
    driver: local

networks:
  windblog_network:
    driver: bridge
