version: "3.9"
services:
  windblog:
    image: ghcr.io/skyhhjmk/windblog:master
    container_name: windblog
    environment:
      - APP_ENV=prod
      - APP_PORT=8787
      - TZ=Asia/Shanghai
    ports:
      - "8787:8787"
    volumes:
      - ./public/uploads:/app/public/uploads
      - ./runtime:/app/runtime
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8787"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: unless-stopped